# Copyright (C) 2017-2025 Smart Code OOD 203358507
name: Flatpak Release

on:
  push:
    tags:
      - 'v*'

jobs:
  flatpak-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Update git submodules
        run: git submodule update --init --recursive
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install build-essential libgtk-3-dev pkg-config libssl-dev libayatana-appindicator3-dev
      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable
      - name: Setup flatpak
        run: |
          sudo apt-get update
          sudo apt-get -y install flatpak-builder
          sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          sudo flatpak install -y org.gnome.Sdk//44
          sudo flatpak install -y org.gnome.Platform//44
          sudo flatpak install -y org.freedesktop.Sdk.Extension.rust-stable//22.08
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install python modules
        run: python -m pip install toml aiohttp
      - name: Build
        run: sh ./build-flatpak.sh
      - name: Get current date
        id: date
        run: echo "TODAY_DATE=$(date +'%d %b %Y')" >> $GITHUB_OUTPUT
      - name: Upload flatpak to release
        uses: softprops/action-gh-release@v1
        with:
          # Use the same name as all releases!
          name: Stremio Service ${{ github.ref_name }} (${{ steps.date.outputs.TODAY_DATE }})
          draft: true
          prerelease: false
          fail_on_unmatched_files: true
          files: |
            flatpak/com.stremio.Service.flatpak
